### ISSUE TITLE
stringListListToDict()

### ISSUE THREAD

**Issue by dekuntz** [wsadminlib/wsadminlib#14]
The following test case fails:
```
stringListListToDict(AdminTask.getUserRegistryInfo('[-userRegistryType WIMUserRegistry]'))['ignoreCase'] 
```
The string returned from getUserRegistryInfo() includes null values in the form of [ [foo bar] [bar ] ] that are not handled correctly. Additionally, the exception handling is broken.

See pull request: Update stringListListToDict #13

**Comment by wsadminlib** [comment]
Hi  @dekuntz 
Please contact me at dingsor at us.ibm.com to discuss the contributor license agreement mentioned here:  https://github.com/wsadminlib/wsadminlib/blob/master/LICENSE
Thanks.

**Comment by dekuntz** [comment]
Check your email for a signed agreement.

**Comment by dekuntz** [comment]
#13 closes this issues. Thanks!
