### ISSUE TITLE
setInitialStateOfAllListenerPortsInCluster() cannot work as designed

### ISSUE THREAD

**Issue by dekuntz** [wsadminlib/wsadminlib#24]
I don't see how `setInitialStateOfAllListenerPortsInCluster()` can work as designed. The function makes use of `listListenerPortsOnServer()` which returns JMX object names. However, the function attempts to use a JMX object name with `AdminConfig.showAttribute()` which expects a configuration ID.
```
lPorts = listListenerPortsOnServer( nodeName, serverName )
for lPort in lPorts:
     sop(m, "Setting ListenerPort %s initial state to %s" % (lPort, state))
     stateManagement = AdminConfig.showAttribute( lPort, "stateManagement" )
```

**Comment by gpoul** [comment]
good catch!

**Comment by dekuntz** [comment]
submitted pull request #26.
