### ISSUE TITLE
Fixme for setCustomProperty should be solved

### ISSUE THREAD

**Issue by kurtdb** [wsadminlib/wsadminlib#6]
The setCustomProperty contains a fixme statement. When I tried to use it, it gave me an error message saying that certain properties could not be found for the name I gave.

My use case was that I had to set a lot of custom properties on the DB2 datasource, since the script does not set them by default. (when you configure the datasource using the web application the properties are set)

I managed to get the properties to work using the following code:

#Configures a custom datasource property. Right now all the properties are set as strings, beware of this!
def definieerCustomDataSourceProperty(dataSource, key, value):
	name = ['name', key]
	type = ['type', 'java.lang.String']
	description = ['description', ""]
	val = ['value', value]
	convertedValue = [name, type, description, val]
	setFixedCustomProperty(dataSource, convertedValue)
	AdminConfig.save()

#Fixed version for the wsadminlib library, since that one does not work for my use case.
def setFixedCustomProperty(object_id, value):
    propSet = AdminConfig.showAttribute(object_id, 'propertySet')
    AdminConfig.create('J2EEResourceProperty', propSet, value)

Currently I can't create a pull request due to timing constraints.

**Comment by kurtdb** [comment]
I tried using the setJ2eeResourceProperty() method, but although it didn't give me an error it also didn't deliver the result I expected. (this being that a custom property was created)

I do agree that my solution isn't 100% foolproof for every situation, but by posting this solution that worked for me I wanted to help other people that might also have the same problem. Extending the solution to incorporate other parameters shouldn't be that much work.

**Comment by gpoul** [comment]
I'm sorry to hear that the setJ2eeResourceProperty() method isn't working for you. Can you share the code you used that didn't fail, but also didn't work correctly?

In addition I'd ask you to share the error that you saw initially for setCustomProperty() and the code you used? That would make it easier to find out why it failed for you.

**Comment by gpoul** [comment]
Please provide your feedback when you get a chance!

**Comment by gpoul** [comment]
@wsadminlib this has been open for a long time with no feedback; what do you think? Could you close it until more feedback is available and we verified whether it is still an issue?

**Comment by wsadminlib** [comment]
Closing this old issue until more feedback is available.  
Thanks to gpoul for the suggestion.
