### ISSUE TITLE
wrapper function setWebContainerCustomProperty

### ISSUE THREAD

**Issue by dekuntz** [wsadminlib/wsadminlib#9]
The function setWebContainerCustomProperty() is a wrapper for setCustomPropertyOnObject(). I noticed that setWebContainerCustomProperty() does not correctly update web container custom properties that already exist. This occurs when there are more than one property. For instance:

setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.foo", "abc123")
setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.bar", "asdf")

setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.foo", "xyz890")
setWebContainerCustomProperty(mynode, server1, "com.ibm.ws.webcontainer.bar", "jkl;")

will result in the creation of a second instance of properties com.ibm.ws.webcontainer.foo and com.ibm.ws.webcontainer.bar.

The problem occurs because setWebContainerCustomProperty() uses getObjectCustomProperty() which is not correctly creating a list object from showAttribute(object_id,'properties'). Specifically, within getObjectCustomProperty():

    x = AdminConfig.showAttribute(object_id,'properties')[1:-1]
    if len(x) == 0:
        return None  # no properties set yet

This is code is checking for '[]' that represents an empty list. However, this causes the if-statement,

    if x.startswith("["):
        propsidlist = x[1:-1].split(' ')

to never return 'True'. Therefore, the split(' ') never gets run to discover the second property contained in x.

I can provide my version of getObjectCustomProperty(object_id, propname) if anyone is interested.

Lastly, is there any difference in using setWebContainerCustomProperty() versus createWebContainerProp()?

**Comment by gpoul** [comment]
I just submitted a pull request that should fix this, but I cannot authoritatively answer your question about whether there is any difference between setWebContainerCustomProperty() and createWebContainerProp()

**Comment by dekuntz** [comment]
Thank you for your fix. It works well in my scripts.
